version: '3'

services:
  node:
    build:
      context: .
      dockerfile: NODE.DOCKERFILE
    volumes:
      - ./appnode:/appnode
      - /appnode/node_modules
    ports:
      - 5002:5002
    networks:
      - invoice-network

  frontend:
    container_name: invoice_v2_react
    build:
      context: .
      dockerfile: FRONT.DOCKERFILE
    environment:
      WATCHPACK_POLLING: 'true'
      WDS_SOCKET_PORT: '3001'
    ports:
      - 3001:3000
    volumes:
      - ./appreact:/appreact
      - /appreact/node_modules
    networks:
      - invoice-network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - invoice-network

networks:
  invoice-network:
    driver: bridge

volumes:
  mysqldata: {}
